spring:
  datasource:
    db: vm_dev
    host: localhost
    port: 5432
    username: user
    password: password

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    io.craigmiller160: DEBUG

video:
  security:
    token:
      key: ThisIsMySecretKeyThisIsMySecretKeyThisIsMySecretKey