spring:
  datasource:
    db: vm_dev
    host: craigmiller160.ddns.net
    port: 30019
    username: ${POSTGRES_ROOT_USER}
    password: ${POSTGRES_ROOT_PASSWORD}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: INFO
    io.craigmiller160: DEBUG
    org.flywaydb: DEBUG

video:
  security:
    token:
      key: ThisIsMySecretKeyThisIsMySecretKeyThisIsMySecretKey

oauth2:
  auth-server-host: https://apps-craigmiller160.ddns.net/oauth2
  client-name: (Dev) video-manager-server
  client-key: ea9156de-f5eb-4ed3-a04a-7baeb26cb59d
  client-secret: 7ab84f05-f2d7-4ed7-9a49-17c6611d8ef0