spring:
  datasource:
    db: vm_dev
    host: localhost
    port: 5432
    username: postgres
    password: password

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: INFO
    io.craigmiller160: DEBUG

video:
  security:
    token:
      key: /RoM6KSD6jiYtYUOmd1klD4dtzpKs6vxJbLWT8DjsbM=

keycloak:
  realm: apps-dev
  credentials:
    secret: oIKLhWa2ORO61KLBUiVovBaSSw6cqXGZ