spring:
  datasource:
    db: vm_dev
    host: craigmiller160.ddns.net
    port: 30019
    username: ${POSTGRES_ROOT_USER}
    password: ${POSTGRES_ROOT_PASSWORD}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: INFO
    io.craigmiller160: DEBUG

video:
  security:
    token:
      key: /RoM6KSD6jiYtYUOmd1klD4dtzpKs6vxJbLWT8DjsbM=

keycloak:
  realm: apps-dev
  credentials:
    secret: oIKLhWa2ORO61KLBUiVovBaSSw6cqXGZ