app_deployment:
  appName: video-manager-server
  image: nexus-docker-craigmiller160.ddns.net/video-manager-server:latest
  configMap:
    spring.profiles.active: prod
    spring.config.location: classpath:/config/common/,classpath:/config/prod/
    spring.datasource.host: postgres.infra-prod
    spring.datasource.port: "5432"
    video.converterUrl: http://video-manager-converter:8080/video-converter
  onepassworditems:
    - name: video-manager-server-oauth2-keys
      itemPath: vaults/Home Server (Prod)/items/Video Manager Server OAuth2 Keys
    - name: video-manager-server-video-token-key
      itemPath: vaults/Home Server (Prod)/items/VideoManager Video Token Key
    - name: video-manager-postgres
      itemPath: vaults/Home Server (Prod)/items/Postgres Root Account
  ports:
    - containerPort: 8443
  secrets:
    - envVariable: spring.datasource.username
      secretName: video-manager-postgres
      secretKey: username
    - envVariable: spring.datasource.password
      secretName: video-manager-postgres
      secretKey: password
    - envVariable: keycloak.resource
      secretName: video-manager-server-oauth2-keys
      secretKey: kcClientId
    - envVariable: keycloak.credentials.secret
      secretName: video-manager-server-oauth2-keys
      secretKey: kcClientSecret
    - envVariable: video.security.token.key
      secretName: video-manager-server-video-token-key
      secretKey: key
  commonProbe:
    httpGet:
      path: /actuator/health
      port: 8443
      scheme: HTTPS
  volumes:
    - name: video-manager-server-volume-homedir
      type: HostPath
      deploymentMountPath: /opt/video-manager/homeDir
      hostPath: /home/craig