spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.hbm2ddl.delimiter: ';'
      hibernate.dialect: org.hibernate.dialect.PostgreSQL9Dialect
      javax.persistence.schema-generation.create-source: metadata
      javax.persistence.schema-generation.scripts.action: drop-and-create
      javax.persistence.schema-generation.scripts.create-target: sql/create-schema.sql
      javax.persistence.schema-generation.scripts.drop-target: sql/drop-schema.sql
    generate-ddl: true
  datasource:
    jdbc-url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}
    url: ${spring.datasource.jdbc-url}/${spring.datasource.db}
    docker: true
  mvc:
    dispatch-options-request: true

cors:
  origins: http://localhost:3000

server:
  session:
    timeout: -1
  servlet:
    session:
      cookie:
        name: VM-SESSIONID
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:cert/video-server.p12
    key-store-password: d?ba5#?&WA#dSy}LQ(51
    enabled: true
    protocol: TLS
    enabled-protocols: TLSv1.2,TLSv1.3
    ciphers: ECDHE-ECDSA-AES256-GCM-SHA384,ECDHE-RSA-AES256-GCM-SHA384,ECDHE-ECDSA-CHACHA20-POLY1305,ECDHE-RSA-CHACHA20-POLY1305,ECDHE-ECDSA-AES128-GCM-SHA256,ECDHE-RSA-AES128-GCM-SHA256,ECDHE-ECDSA-AES256-SHA384,ECDHE-RSA-AES256-SHA384,ECDHE-ECDSA-AES128-SHA256,ECDHE-RSA-AES128-SHA256

logging:
  level:
    root: ERROR
    org.springframework: INFO
    org.hibernate: INFO
    io.craigmiller160: INFO
    io.craigmiller160.webutils: DEBUG
  file:
    common-path: video-manager/server-logs/${spring.profiles.active}.log
    path: ${HOME}/${logging.file.common-path}


video:
  vlcCommand: vlc
  apiPageSize: 10
  fileExts: mp4,m4v
  security:
    password:
      hashRounds: 12
    token:
      expSecs: 300
      refreshExpSecs: 1200
      keySizeBits: 256
      videoExpSecs: 21600

localfile:
  homeDir: ${user.home}

oauth2:
  cookie-name: vm_token
  cookie-max-age-secs: 86400
  client-name: video-manager-server
  auth-login-base-uri: "/video-manager/oauth2"
  auth-code-redirect-uri: "/video-manager/api/oauth/authcode/code"
  post-auth-redirect: "/video-manager"
  auth-code-wait-mins: 10
  insecure-paths: "/api/actuator/health"
