package io.craigmiller160.videomanagerserver.repository

import io.craigmiller160.videomanagerserver.dto.VideoFile
import org.springframework.data.repository.PagingAndSortingRepository

interface VideoFileRepository : PagingAndSortingRepository<VideoFile,Long>