apiVersion: v1
kind: ConfigMap
metadata:
  name: video-manager-server-config
data:
  spring.profiles.active: prod
  spring.config.location: classpath:/config/common/,classpath:/config/prod/
  spring.datasource.host: postgres.infra-prod
  spring.datasource.port: "5432"
  oauth2.auth-server-host: https://sso-oauth2-server:8443
  # TODO remove this
  logging.level.org.flywaydb: DEBUG
  spring.flyway.enabled: "true"
