spring:
  datasource:
    db: vm_prod
    host: postgres

cors:
  origins: http://localhost:9000

logging:
  file:
    path: /opt/${logging.file.path}

localfile:
  homeDir: /opt/video-manager/homeDir