spring:
  datasource:
    db: vm_dev
    host: localhost

cors:
  origins: http://localhost:3000

logging:
  file: ${HOME}/${logging.file.path}
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    io.craigmiller160: DEBUG