spring:
  profiles:
    active: @spring.profiles.active@
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url: jdbc:postgresql://${spring.datasource.host}:5432/${spring.datasource.db}
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    docker: true
  mvc:
    dispatch-options-request: true

server:
  servlet:
    context-path: /api
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:cert/video-server.p12
    key-store-password: d?ba5#?&WA#dSy}LQ(51
    protocol: TLS
    enabled-protocols: TLSv1.3,TLSv1.2
    ciphers: TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256,TLS_AES_128_GCM_SHA256,DHE-RSA-AES256-GCM-SHA384,DHE-RSA-AES128-GCM-SHA256,ECDHE-RSA-AES256-GCM-SHA384,ECDHE-RSA-AES128-GCM-SHA256


logging:
  level:
    root: ERROR
    org.springframework: INFO
    org.hibernate: INFO
    io.craigmiller160: INFO
  file:
    common-path: video-manager/server-logs/${spring.profiles.active}.log
    path: ${HOME}/${logging.file.common-path}


video:
  vlcCommand: vlc
  apiPageSize: 10
  fileExts: mp4,m4v
  security:
    password:
      hashRounds: 12
    token:
      expSecs: 300
      refreshExpSecs: 1200
      keySizeBits: 256
      videoExpSecs: 21600

localfile:
  homeDir: ${user.home}