spring:
  datasource:
    db: vm_qa
    host: localhost
    port: 30001
    username: user
    password: password

oauth2:
  auth-server-host: https://localhost:7003
  client-key: ba8ea173-b5eb-4ccf-9ca6-0ea7c3b4b417
  client-secret: fa618231-49e1-47cf-8edf-d406832d6ead