spring:
  datasource:
    db: vm_prod
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      javax.persistence.schema-generation.scripts.action: none
cors:
  origins: http://localhost:9000

logging:
  file:
    path: /opt/${logging.file.common-path}

localfile:
  homeDir: /opt/video-manager/homeDir

oauth2:
  client-name: video-manager-server
