apiVersion: v1
kind: ConfigMap
metadata:
  name: video-manager-server-config
data:
  spring.profiles.active: prod
  spring.config.location: classpath:/config/common/,classpath:/config/prod/
  spring.datasource.host: postgres-service
  spring.datasource.port: "5432"
  spring.datasource.username: postgres_root
  oauth2.auth-server-host: https://sso-oauth2-server-service:8443
  oauth2.client-key: 932a25e5-0071-4174-b33f-ea0e8170c470
