apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-manager-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-manager-server
  template:
    metadata:
      labels:
        app: video-manager-server
    spec:
      containers:
        - name: video-manager-server
          image: localhost:32000/video-manager-server:1.12.1
          ports:
            - containerPort: 8443
          envFrom:
            - configMapRef:
                name: video-manager-server-config
          volumeMounts:
            - mountPath: /opt/video-manager/homeDir
              name: video-manager-server-volume-homedir
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 300
      volumes:
        - name: video-manager-server-volume-homedir
          hostPath:
            path: /opt/kubernetes/data/video-manager-server/homeDir
---
apiVersion: v1
kind: Service
metadata:
  name: video-manager-server-service
spec:
  type: ClusterIP
  selector:
    app: video-manager-server
  ports:
    - port: 8443
      targetPort: 8443
      protocol: TCP
