apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-manager-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-manager-server
  template:
    metadata:
      labels:
        app: video-manager-server
    spec:
      containers:
        - name: video-manager-server
          image: craigmiller160.ddns.net:30004/video-manager-server:1.15.0-SNAPSHOT
          ports:
            - containerPort: 8443
          envFrom:
            - configMapRef:
                name: video-manager-server-config
          env:
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: postgres-root-password
                  key: POSTGRES_ROOT_PASSWORD
            - name: oauth2.client-secret
              valueFrom:
                secretKeyRef:
                  name: video-manager-server-client-secret
                  key: client-secret
          volumeMounts:
            - mountPath: /opt/video-manager/homeDir
              name: video-manager-server-volume-homedir
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 300
      volumes:
        - name: video-manager-server-volume-homedir
          hostPath:
            path: /opt/kubernetes/data/video-manager-server/homeDir
---
apiVersion: v1
kind: Service
metadata:
  name: video-manager-server-service
spec:
  type: ClusterIP
  selector:
    app: video-manager-server
  ports:
    - port: 8443
      targetPort: 8443
      protocol: TCP
